### ISSUE TITLE
Pass `--force` flag to ansible-galaxy command

### ISSUE THREAD

**Issue by drmatthews** [arillso/action.playbook#41]
Many thanks for making this very useful Github action available to the community!

When running in a container on a self-hosted running there is some caching that occurs and it would be nice to be able to pass `--force` to the `ansible-galaxy` command in order to update previously installed roles and collections. I don't think this is currently an option (or may I missed it).

**Comment by sbaerlocher** [comment]
The function is already integrated!

You can use the `galaxy_force` parameter to pass the `--force` flag to the `ansible-galaxy` command. Here's an example:

```yaml
- name: Play Ansible Playbook
  uses: arillso/action.playbook@main
  with:
    playbook: tests/playbook.yml
    inventory: tests/hosts.yml
    galaxy_file: tests/requirements.yml
    galaxy_force: true
  env:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_DEPRECATION_WARNINGS: 'false'
```

The `galaxy_force` parameter specifically "Forces the reinstallation of roles or collections from the Galaxy file," which is exactly what the `--force` flag does. Simply set it to `true` to enable this functionality.
